language: node_js

node_js:
  - '0.12'
  - '0.10'
  - '4.0.0'

services:
  - redis
  - mongodb

script:
  - npm run cover

after_script: "cat coverage/lcov.info | node_modules/coveralls/bin/coveralls.js"
